classes:
- system.linux.system.repo.mcp.salt
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.ubuntu
- system.linux.system.repo.glusterfs
- system.openssh.client.lab
- system.glusterfs.client.cluster
- system.glusterfs.client.volume.salt_pki
- system.salt.master.pkg
- system.salt.minion.ca.salt_master
- system.salt.master.api
- system.reclass.storage.salt
- system.xtrabackup.server.single
- system.reclass.storage.system.physical_control_cluster
- system.reclass.storage.system.infra_maas_single
- system.reclass.storage.system.openstack_control_cluster
- system.reclass.storage.system.openstack_database_cluster
- cluster.neutron-ovs-dpdk.infra
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: "https://github.com/AKamyshnikova/mcp-intel-lab-model.git"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    deploy_address: ${_param:infra_config_deploy_address}
    linux_system_codename: xenial
    salt_api_password_hash: "<<WILL_BE_GENERATED>>"
    salt_master_host: ${_param:infra_config_address}
  reclass:
    storage:
      node:
        infra_kvm_node01:
          params:
            keepalived_vip_priority: 100
            linux_system_codename: xenial
        infra_kvm_node02:
          params:
            keepalived_vip_priority: 101
            linux_system_codename: xenial
        infra_kvm_node03:
          params:
            keepalived_vip_priority: 102
            linux_system_codename: xenial
        openstack_control_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.control_init
          params:
            linux_system_codename: xenial
        openstack_control_node02:
          params:
            linux_system_codename: xenial
        openstack_control_node03:
          params:
            linux_system_codename: xenial
        openstack_database_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.database_init
          params:
            linux_system_codename: xenial
        openstack_database_node02:
          params:
            linux_system_codename: xenial
        openstack_database_node03:
          params:
            linux_system_codename: xenial
        openstack_gateway_node01:
          name: gtw01
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.gateway
          params:
            linux_system_codename: xenial
            public_address: 172.16.98.2
            single_address: 192.168.20.224
            tenant_address: 10.0.2.6
            deploy_address: 192.168.10.224
            salt_master_host: 192.168.10.15
        #openstack_gateway_node02:
        #  name: gtw02
        #  domain: ${_param:cluster_domain}
        #  classes:
        #  - cluster.${_param:cluster_name}.openstack.gateway
        #  params:
        #    linux_system_codename: xenial
        #    public_address: 172.16.98.3
        #openstack_gateway_node03:
        #  name: gtw03
        #  domain: ${_param:cluster_domain}
        #  classes:
        #  - cluster.${_param:cluster_name}.openstack.gateway
        #  params:
        #    linux_system_codename: xenial
        #    public_address: 172.16.98.4
        openstack_compute_rack01:
          name: ${_param:openstack_compute_rack01_hostname}<<count>>
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.compute.dpdk
          repeat:
            count: 2
            start: 1
            digits: 3
            params:
              single_address:
                value: ${_param:openstack_compute_rack01_single_subnet}.<<count>>
                start: 101
              tenant_address:
                value: ${_param:openstack_compute_rack01_tenant_subnet}.<<count>>
                start: 101
              deploy_address:
                value: ${_param:openstack_compute_rack01_deploy_subnet}.<<count>>
                start: 101
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            dpdk0_name: ens801f0
            dpdk1_name: ens801f1
            dpdk0_pci: '"0000:82:00.0"'
            dpdk1_pci: '"0000:82:00.1"'
            primary_first_nic: eno1
            primary_second_nic: eno2
            compute_ovs_pmd_cpu_mask: '"0x3ffffc00000"'
            nova_pmd_rxq_affinity: "0:22,1:23,2:24,3:25,4:26,5:27,6:28,7:29,8:30,9:31"
        openstack_compute_rack02:
          name: ${_param:openstack_compute_rack01_hostname}<<count>>
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.compute.dpdk
          repeat:
            count: 1
            start: 3
            digits: 3
            params:
              single_address:
                value: ${_param:openstack_compute_rack01_single_subnet}.<<count>>
                start: 103
              tenant_address:
                value: ${_param:openstack_compute_rack01_tenant_subnet}.<<count>>
                start: 103
              deploy_address:
                value: ${_param:openstack_compute_rack01_deploy_subnet}.<<count>>
                start: 103
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            dpdk0_name: enp24s0f0
            dpdk1_name: enp24s0f1
            dpdk0_pci: '"0000:18:00.0"'
            dpdk1_pci: '"0000:18:00.1"'
            nova_cpu_pinning: 42,43,44,45,46,47,48,49,50,51,52,53,54,55
            compute_ovs_pmd_cpu_mask: '"0x7ffc000"'
            primary_first_nic: enp67s0f0
            primary_second_nic: enp67s0f1
            nova_pmd_rxq_affinity: "0:14,1:15,2:16,3:17,4:18,5:19,6:20,7:21,8:22,9:23"
        openstack_compute_node4:
            name: cmp004
            domain: ${_param:cluster_domain}
            classes:
            - cluster.${_param:cluster_name}.openstack.compute.dpdk
            params:
              linux_system_codename: xenial
              single_address: 192.168.20.104
              tenant_address: 10.0.2.104
              deploy_address: 192.168.10.104
              salt_master_host: 192.168.10.15
              dpdk0_name: enp24s0f0
              dpdk1_name: enp24s0f1
              dpdk0_pci: '"0000:18:00.0"'
              dpdk1_pci: '"0000:18:00.1"'
              nova_cpu_pinning: 54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71
              compute_ovs_pmd_cpu_mask: '"0x3fffc0000"'
              primary_first_nic: enp67s0f0
              primary_second_nic: enp67s0f1
              nova_pmd_rxq_affinity: "0:18,1:19,2:20,3:21,4:22,5:23,6:24,7:25,8:26,9:27"
