
classes:
- system.linux.system.single
- system.openssh.server.team.lab
- system.openssh.server.team.mcp_qa
- system.openssh.server.team.networking
- cluster.neutron-ovs-dpdk._team
- cluster.neutron-ovs-dpdk.openstack
parameters:
  _param:
    salt_control_trusty_image: http://apt-mk.mirantis.com/images/ubuntu-14-04-x64-mcp1.1.qcow2
    salt_control_xenial_image: http://apt-mk.mirantis.com/images/ubuntu-16-04-x64-mcp1.1.qcow2
    infra_config_hostname: cfg01
    salt_minion_ca_host: ${_param:infra_config_hostname}.${_param:cluster_domain}
    # infra service addresses
    infra_config_address: 192.168.10.15
    infra_config_deploy_address: 192.168.10.15

    cluster_domain: neutron-ovs-dpdk.local
    cluster_name: neutron-ovs-dpdk
    cluster_public_host: ${_param:openstack_proxy_address}

    # MaaS parameters
    infra_maas_node01_deploy_address: 192.168.10.91
    infra_maas_node01_hostname: mas01
    maas_admin_username: mirantis
    maas_admin_password: YrbGQJbs0bIE46Kw
    maas_db_password: aIvTzUhCbROp
    maas_url: http://172.16.98.5:5240/MAAS

    infra_kvm_address: 192.168.10.240
    infra_kvm_node01_address: 192.168.20.241
    infra_kvm_node02_address: 192.168.20.242
    infra_kvm_node03_address: 192.168.20.243
    infra_kvm_node01_deploy_address: 192.168.10.241
    infra_kvm_node02_deploy_address: 192.168.10.242
    infra_kvm_node03_deploy_address: 192.168.10.243
    infra_kvm_node01_hostname: kvm01
    infra_kvm_node02_hostname: kvm02
    infra_kvm_node03_hostname: kvm03

    glusterfs_node01_address: ${_param:infra_kvm_node01_address}
    glusterfs_node02_address: ${_param:infra_kvm_node02_address}
    glusterfs_node03_address: ${_param:infra_kvm_node03_address}

    control_network_netmask: 255.255.255.0
    control_vlan: 102

    tenant_network_netmask: 255.255.255.0

    dns_server01: 8.8.8.8
    dns_server02: 8.8.4.4
    deploy_network_netmask: 255.255.255.0
    deploy_network_gateway: 192.168.10.91

    public_network: 172.16.98.0/24
    public_network_netmask: 255.255.255.0
    public_network_gateway: 172.16.98.1
    public_vlan: 103
    # public node addresses 172.16.98.2-172.16.98.20
    public_gtw01_address: 172.16.98.2
    public_gtw02_address: 172.16.98.3
    public_gtw02_address: 172.16.98.4

    linux_dhcp_interface:
      enabled: true
      type: eth
      proto: dhcp
      gateway: ${_param:deploy_network_gateway}
      name_servers:
        - ${_param:dns_server01}
        - ${_param:dns_server02}
    linux_single_interface:
      enabled: true
      type: eth
      proto: static
      address: ${_param:single_address}
      netmask: ${_param:control_network_netmask}

    bond_purley:
      name: "bond0"
      enabled: true
      proto: manual
      type: bond
      use_interfaces:
      - ${_param:primary_first_nic}
      - ${_param:primary_second_nic}
      - ${_param:primary_third_nic}
      - ${_param:primary_forth_nic}
      slaves: ${_param:primary_first_nic} ${_param:primary_second_nic} ${_param:primary_third_nic} ${_param:primary_forth_nic}
      mode: 802.3ad

    bond_broadwell:
      name: "bond0"
      enabled: true
      proto: manual
      type: bond
      use_interfaces:
      - ${_param:primary_first_nic}
      - ${_param:primary_second_nic  }
      slaves: ${_param:primary_first_nic} ${_param:primary_second_nic}
      mode: 802.3ad

    purley_interfaces:
      eno3:
        enabled: true
        type: slave
        proto: manual
        name: ${_param:primary_third_nic}
        master: bond0
      eno2:
        enabled: true
        type: slave
        proto: manual
        name: ${_param:primary_forth_nic}
        master: bond0


  salt:
    minion:
      trusted_ca_minions:
        - ${_param:salt_minion_ca_host}

  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
        cfg:
          address: ${_param:infra_config_address}
          names:
          - cfg
          - cfg.${_param:cluster_domain}
        kvm01:
          address: ${_param:infra_kvm_node01_address}
          names:
          - ${_param:infra_kvm_node01_hostname}
          - ${_param:infra_kvm_node01_hostname}.${_param:cluster_domain}
        kvm02:
          address: ${_param:infra_kvm_node02_address}
          names:
          - ${_param:infra_kvm_node02_hostname}
          - ${_param:infra_kvm_node02_hostname}.${_param:cluster_domain}
        kvm03:
          address: ${_param:infra_kvm_node03_address}
          names:
          - ${_param:infra_kvm_node03_hostname}
          - ${_param:infra_kvm_node03_hostname}.${_param:cluster_domain}
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
      service:
        apt-daily.timer:
          status: dead
